name: Sablier V2
contracts:
  - name: SablierV2LockupLinear
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event: CancelLockupStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint128 senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient, (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint40,uint40,uint40) range, address broker)
        requiredEntities:
          - name: Asset
          - name: Contract
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
networks:
  - id: 1 # Ethereum
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0xB10daee1FCF62243aE27776D7a92D39dC8740f95
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0x39EFdC3dbB57B2388CcC4bb40aC4CB1226Bc9E44
  - id: 42161 # Arbitrum
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x197D655F3be03903fD25e7828c3534504bfe525e
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0xA9EfBEf1A35fF80041F567391bdc9813b2D50197
  - id: 43114 # Avalanche
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x610346E9088AFA70D6B03e96A800B3267E75cA19
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0x665d1C8337F1035cfBe13DD94bB669110b975f5F
  - id: 8453 # Base
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x6b9a46C8377f21517E65fa3899b3A9Fab19D17f5
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0x645B00960Dc352e699F89a81Fc845C0C645231cf
  - id: 56 # BSC
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x3FE4333f62A75c2a85C8211c6AeFd1b9Bfde6e51
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0xF2f3feF2454DcA59ECA929D2D8cD2a8669Cc6214
  - id: 100 # Gnosis
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x685E92c9cA2bB23f1B596d0a7D749c0603e88585
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0xeb148E4ec13aaA65328c0BA089a278138E9E53F9
  - id: 10 # Optimism
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0xB923aBdCA17Aed90EB5EC5E407bd37164f632bFD
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0x6f68516c21E248cdDfaf4898e66b2b0Adee0e0d6
  - id: 137 # Polygon
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x67422C3E36A908D5C3237e9cFfEB40bDE7060f6E
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0x7313AdDb53f96a4f710D3b91645c62B434190725
  - id: 534352 # Scroll
    start_block: 0
    contracts:
      - name: SablierV2LockupLinear
        address:
          - 0x80640ca758615ee83801EC43452feEA09a202D33
      # - name: SablierV2LockupDynamic
      #   address:
      #     - 0xde6a30D851eFD0Fc2a9C922F294801Cfd5FCB3A1
