# https://github.com/sablier-labs/v2-docs/blob/main/docs/contracts/v2/02-deployments.md
name: Sablier V2.1
contracts:
  - name: SablierV2Lockup
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event: CancelLockupStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint128 senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient, (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint40,uint40,uint40) range, address broker)
        requiredEntities:
          - name: Asset
          - name: Contract
          - name: Watcher
      - event: CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient, (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint128,uint64,uint40)[] segments, (uint40,uint40) range, address broker)
        requiredEntities:
          - name: Asset
          - name: Contract
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
  - name: SablierV21Lockup
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event: CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset, uint128 senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient, (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable, (uint40,uint40,uint40) range, address broker)
        requiredEntities:
          - name: Asset
          - name: Contract
          - name: Watcher
      - event: CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient, (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable, (uint128,uint64,uint40)[] segments, (uint40,uint40) range, address broker)
        requiredEntities:
          - name: Asset
          - name: Contract
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
networks:
  - id: 1 # Ethereum
    start_block: 0
    contracts:
      - name: SablierV2Lockup
        address:
          - 0xB10daee1FCF62243aE27776D7a92D39dC8740f95 # v2.0
          - 0x39EFdC3dbB57B2388CcC4bb40aC4CB1226Bc9E44 # v2.0
      - name: SablierV21Lockup
        address:
          - 0xAFb979d9afAd1aD27C5eFf4E27226E3AB9e5dCC9 # v2.1
          - 0x7CC7e125d83A581ff438608490Cc0f7bDff79127 # v2.1
  # - id: 42161 # Arbitrum
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  #         - 0x197D655F3be03903fD25e7828c3534504bfe525e # v2.0
  #         - 0xA9EfBEf1A35fF80041F567391bdc9813b2D50197 # v2.0
  #         - 0xFDD9d122B451F549f48c4942c6fa6646D849e8C1 # v2.1
  #         - 0xf390cE6f54e4dc7C5A5f7f8689062b7591F7111d # v2.1
  # - id: 43114 # Avalanche todo: check relevance
  # start_block: 0
  # contracts:
  #   - name: SablierV2Lockup
  #     address:
  #       - 0x610346E9088AFA70D6B03e96A800B3267E75cA19 # v2.0
  #       - 0x665d1C8337F1035cfBe13DD94bB669110b975f5F # v2.0
  # - id: 8453 # Base
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  # - 0x6b9a46C8377f21517E65fa3899b3A9Fab19D17f5 # v2.0
  # - 0x645B00960Dc352e699F89a81Fc845C0C645231cf # v2.0
  #         - 0xFCF737582d167c7D20A336532eb8BCcA8CF8e350 # v2.1
  #         - 0x461E13056a3a3265CEF4c593F01b2e960755dE91 # v2.1
  # - id: 56 # BSC
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  #         - 0x3FE4333f62A75c2a85C8211c6AeFd1b9Bfde6e51 # v2.0
  #         - 0xF2f3feF2454DcA59ECA929D2D8cD2a8669Cc6214 # v2.0
  #         - 0x14c35E126d75234a90c9fb185BF8ad3eDB6A90D2 # v2.1
  #         - 0xf900c5E3aA95B59Cc976e6bc9c0998618729a5fa # v2.1
  # - id: 100 # Gnosis
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  # - 0x685E92c9cA2bB23f1B596d0a7D749c0603e88585 # v2.0
  # - 0xeb148E4ec13aaA65328c0BA089a278138E9E53F9 # v2.0
  #         - 0xce49854a647a1723e8Fb7CC3D190CAB29A44aB48 # v2.1
  #         - 0x1DF83C7682080B0f0c26a20C6C9CB8623e0Df24E # v2.1
  # - id: 10 # Optimism
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  #   - 0xB923aBdCA17Aed90EB5EC5E407bd37164f632bFD # v2.0
  #   - 0x6f68516c21E248cdDfaf4898e66b2b0Adee0e0d6 # v2.0
  #         - 0x4b45090152a5731b5bc71b5baF71E60e05B33867 # v2.1
  #         - 0xd6920c1094eABC4b71f3dC411A1566f64f4c206e # v2.1
  # - id: 137 # Polygon
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  # - 0X67422C3E36A908D5C3237E9CFFEB40BDE7060F6E # v2.0
  # - 0x7313AdDb53f96a4f710D3b91645c62B434190725 # v2.0
  #         - 0x5f0e1dea4A635976ef51eC2a2ED41490d1eBa003 # v2.1
  #         - 0xB194c7278C627D52E440316b74C5F24FC70c1565 # v2.1
  # - id: 534352 # Scroll
  #   start_block: 0
  #   contracts:
  #     - name: SablierV2Lockup
  #       address:
  # - 0x80640ca758615ee83801EC43452feEA09a202D33 # v2.0
  # - 0xde6a30D851eFD0Fc2a9C922F294801Cfd5FCB3A1 # v2.0
  #         - 0x57e14AB4DAd920548899d86B54AD47Ea27F00987 # v2.1
  #         - 0xAaff2D11f9e7Cd2A9cDC674931fAC0358a165995 # v2.1
